/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Process;

import com.sun.org.apache.bcel.internal.generic.Select;
import java.awt.event.KeyEvent;
import java.util.Optional;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author yuman
 */
public class CarListUpdate extends javax.swing.JFrame {

    /**
     * Creates new form CarSelection
     */
    public CarListUpdate() {
        initComponents();
        setLocationRelativeTo(null);
        addRowToJTable();
    }
    public class Isitabel{
        public String license;
        public String brand;
        public String production;
        public String type;
        public String color;
        public int price;
        
        public Isitabel(String License, String Brand, String Production, String Type,String Color, int Price )
        {
            this.license = License;
            this.brand = Brand;
            this.production = Production;
            this.type = Type;
             this.color = Color;
            this.price = Price;
        }
    }
    
     public ArrayList Isitabell()
    {
        ArrayList<Isitabel> list = new ArrayList<Isitabel>();
        Isitabel u1 = new Isitabel("BP 1309 GD","Toyota","2012","Avanza","Black",300000);
        Isitabel u2 = new Isitabel("B 1481 UKS","Daihatsu","2008","Xenia","Silver",315000);
        Isitabel u3 = new Isitabel("DD 4419 KF","Toyota","2013","Avanza","Black",350000);
        Isitabel u4 = new Isitabel("B 1979 KP","Honda","2011","Jazz","Red",270000);
        Isitabel u5 = new Isitabel("D 1766 SS","Honda","2010","Freed","White",290000);
        Isitabel u6 = new Isitabel("AA 8827 HZ","Daihatsu","2010","Luxio","Black",400000);
        Isitabel u7 = new Isitabel("B 1934 TAU","Toyota","2009","Yaris","White",280000);
        Isitabel u8 = new Isitabel("F 8277 BAU","Honda","2015","Mobilio","Silver",320000);
        Isitabel u9 = new Isitabel("A 1222 CD","Daihatsu","2009","Xenia","Red",350000);
        Isitabel u10 = new Isitabel("H 8222 RA","Toyota","2011","Yaris","White",320000);
        list.add(u1);
        list.add(u2);
        list.add(u3);
        list.add(u4);
        list.add(u5);
        list.add(u6);
        list.add(u7);
        list.add(u8);
        list.add(u9);
        list.add(u10);
        return list;
    }
  
     
         public void addRowToJTable()
    {
        DefaultTableModel tblModel = (DefaultTableModel) table2.getModel();
        ArrayList<Isitabel> list = Isitabell();
        Object rowData[] = new Object[6];
        for(int i = 0; i < list.size(); i++)
        {
            rowData[0] = list.get(i).license;
            rowData[1] = list.get(i).brand;
            rowData[2] = list.get(i).production;
            rowData[3] = list.get(i).type;
            rowData[4] = list.get(i).color;
            rowData[5] = list.get(i).price;
            tblModel.addRow(rowData);
        }
                
    }
            /**
     * 
     * 
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        License = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        txtLicense = new javax.swing.JTextField();
        txtBrand = new javax.swing.JComboBox<>();
        type = new javax.swing.JLabel();
        production = new javax.swing.JLabel();
        txtProduction = new javax.swing.JComboBox<>();
        txtType = new javax.swing.JComboBox<>();
        price = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        color = new javax.swing.JLabel();
        txtColor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setText("Car List Update");

        License.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        License.setText("LICENSE PLATE");

        brand.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        brand.setText("BRAND");

        txtBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select Brand...", "Toyota", "Daihatsu", "Honda" }));
        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        type.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        type.setText("TYPE");

        production.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        production.setText("PRODUCTION YEAR");

        txtProduction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select Year..", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));

        txtType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select Type...", "Avanza", "Xenia", "Freed", "Mobilio", "Luxio", "Yaris", "Jazz" }));
        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });

        price.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        price.setText("PRICE / DAY");

        txtPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPriceKeyPressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4047317_auto_automobile_car_sedan_transport_icon.png"))); // NOI18N

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LICENSE PLATE", "BRAND", "PRODUCTION YEAR", "TYPE", "COLOR", "PRICE"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table2);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4213475_arrow_back_left_return_icon.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        color.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        color.setText("COLOR");

        txtColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select Color..", "Red", "White", "Black", "Silver" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(brand)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(License, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(169, 169, 169)
                                        .addComponent(production, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(txtProduction, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 48, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(385, 385, 385)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(color))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtColor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(License, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(production, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLicense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProduction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(brand)
                        .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(color)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
       
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int dialogreturn = JOptionPane.showOptionDialog(this, "Are You Sure?", "Return",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);{

            if(dialogreturn == JOptionPane.YES_OPTION){
                Dashbord jf1 = new Dashbord();
                jf1.show();
                dispose();

                if (dialogreturn == JOptionPane.NO_OPTION){
                    remove(dialogreturn);
                }
            }
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String data1,data2,data3,data4,data5,data6;
    DefaultTableModel model = (DefaultTableModel) table2.getModel();
    if(table2.getSelectedRowCount()==1){
        data1=txtLicense.getText();
        data2=txtBrand.getSelectedItem().toString();
        data3=txtProduction.getSelectedItem().toString();
        data4=txtType.getSelectedItem().toString();
        data5=txtColor.getSelectedItem().toString();
        data6=txtPrice.getText();

    table2.setValueAt(data1,table2.getSelectedRow(),0);
     table2.setValueAt(data2,table2.getSelectedRow(),1);
     table2.setValueAt(data3,table2.getSelectedRow(),2);
     table2.setValueAt(data4,table2.getSelectedRow(),3);
     table2.setValueAt(data5,table2.getSelectedRow(),4);
     table2.setValueAt(data6,table2.getSelectedRow(),5);
     
    JOptionPane.showMessageDialog(this,"Update Successfully..");
       data1=txtLicense.getText();
        data2=txtBrand.getSelectedItem().toString();
        data3=txtProduction.getSelectedItem().toString();
        data4=txtType.getSelectedItem().toString();
        data5=txtColor.getSelectedItem().toString();
         data6=txtPrice.getText();
         
         txtLicense.setText("");
    txtBrand.setSelectedIndex(0);
    txtProduction.setSelectedIndex(0);
    txtType.setSelectedIndex(0);
    txtColor.setSelectedIndex(0);
     txtPrice.setText("");
     txtLicense.requestFocus();
    }                                        
    else {
    if(table2.getRowCount()==0){
        
    JOptionPane.showMessageDialog(this,"Table Is Empty..");
    }
    else {
            JOptionPane.showMessageDialog(this,"Please Select Single Row For Update");
            }  
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        String data1,data2,data3,data4,data5,data6;
                
              
         data1=txtLicense.getText();
        data2=txtBrand.getSelectedItem().toString();
        data3=txtProduction.getSelectedItem().toString();
        data4=txtType.getSelectedItem().toString();
        data5=txtColor.getSelectedItem().toString();
         data6=txtPrice.getText();
             
         
         { 
       JOptionPane.showMessageDialog(this,"Input Successfully..");
       
         Object[] row  = {data1,data2,data3,data4,data5,data6};
       DefaultTableModel model=(DefaultTableModel) table2.getModel();
       model.addRow(row);
       
      txtLicense.setText("");
    txtBrand.setSelectedIndex(0);
    txtProduction.setSelectedIndex(0);
    txtType.setSelectedIndex(0);
     txtColor.setSelectedIndex(0);
     txtPrice.setText("");
     txtLicense.requestFocus();
       
         }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyPressed
       String price = txtPrice.getText();
        int length = price.length();
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<12){
               txtPrice.setEditable(true);
            }else{
             txtPrice.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE  ) {
            txtPrice.setEditable(true);
             
            }else{
              txtPrice.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtPriceKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          DefaultTableModel tblModel = (DefaultTableModel) table2.getModel();
        
        if(table2.getSelectedRowCount()==1){
                         int dialog = JOptionPane.showOptionDialog(this, "Delete This Data?", "Delete",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);{
             if(dialog == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Delete Successfully");
            
             tblModel.removeRow(table2.getSelectedRow());
            txtLicense.setText("");
    txtBrand.setSelectedIndex(0);
    txtProduction.setSelectedIndex(0);
    txtType.setSelectedIndex(0);
    txtColor.setSelectedIndex(0);
     txtPrice.setText("");
     txtLicense.requestFocus();

        if (dialog == JOptionPane.NO_OPTION){
             remove(dialog); }           
        }
        }
        
           
       

            
        }else{
            if(table2.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Table Is Empty..");
            }else{
             JOptionPane.showMessageDialog(this, "Please Select Single Row For Delete");
            }
                      
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
       DefaultTableModel tblModel = (DefaultTableModel)table2.getModel();
        
        String data1 = tblModel.getValueAt(table2.getSelectedRow(),0).toString();
        String data2 = tblModel.getValueAt(table2.getSelectedRow(),1).toString();
        String data3 = tblModel.getValueAt(table2.getSelectedRow(),2).toString();
        String data4 = tblModel.getValueAt(table2.getSelectedRow(),3).toString();
        String data5 = tblModel.getValueAt(table2.getSelectedRow(),4).toString();
        String data6 = tblModel.getValueAt(table2.getSelectedRow(),5).toString();
        
        txtLicense.setText(data1);
        txtBrand.setSelectedItem(data2);
        txtProduction.setSelectedItem(data3);
        txtType.setSelectedItem(data4);
        txtColor.setSelectedItem(data5);
        txtPrice.setText(data6);
        
    }//GEN-LAST:event_table2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       txtLicense.setText("");
    txtBrand.setSelectedIndex(0);
    txtProduction.setSelectedIndex(0);
    txtType.setSelectedIndex(0);
    txtColor.setSelectedIndex(0);
     txtPrice.setText("");
     txtLicense.requestFocus();
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarListUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarListUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarListUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarListUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarListUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel License;
    private javax.swing.JLabel brand;
    private javax.swing.JLabel color;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel production;
    private javax.swing.JTable table2;
    private javax.swing.JComboBox<String> txtBrand;
    private javax.swing.JComboBox<String> txtColor;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JComboBox<String> txtProduction;
    private javax.swing.JComboBox<String> txtType;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
