/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Process;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yuman
 */
public class CarSelection extends javax.swing.JFrame {

    /**
     * Creates new form CarSelection
     */
    public CarSelection() {
        initComponents();
        setLocationRelativeTo(null);
        addRowToJTable();
        
    }

    public class Isitabel{
        public String license;
        public String brand;
        public String production;
        public String type;
        public String color;
        public int price;
        
        public Isitabel(String License, String Brand, String Production, String Type,String Color, int Price )
        {
            this.license = License;
            this.brand = Brand;
            this.production = Production;
            this.type = Type;
             this.color = Color;
            this.price = Price;
        }
    }
    
     public ArrayList Isitabell()
    {
        ArrayList<Isitabel> list = new ArrayList<Isitabel>();
        Isitabel u1 = new Isitabel("BP 1309 GD","Toyota","2012","Avanza","Black",300000);
        Isitabel u2 = new Isitabel("B 1481 UKS","Daihatsu","2008","Xenia","Silver",315000);
        Isitabel u3 = new Isitabel("DD 4419 KF","Toyota","2013","Avanza","Black",350000);
        Isitabel u4 = new Isitabel("B 1979 KP","Honda","2011","Jazz","Red",270000);
        Isitabel u5 = new Isitabel("D 1766 SS","Honda","2010","Freed","White",290000);
        Isitabel u6 = new Isitabel("AA 8827 HZ","Daihatsu","2010","Luxio","Black",400000);
        Isitabel u7 = new Isitabel("B 1934 TAU","Toyota","2009","Yaris","White",280000);
        Isitabel u8 = new Isitabel("F 8277 BAU","Honda","2015","Mobilio","Silver",320000);
        Isitabel u9 = new Isitabel("A 1222 CD","Daihatsu","2009","Xenia","Red",350000);
        Isitabel u10 = new Isitabel("H 8222 RA","Toyota","2011","Yaris","White",320000);
        list.add(u1);
        list.add(u2);
        list.add(u3);
        list.add(u4);
        list.add(u5);
        list.add(u6);
        list.add(u7);
        list.add(u8);
        list.add(u9);
        list.add(u10);
        return list;
    }
  
     
         public void addRowToJTable()
    {
        DefaultTableModel tblModel = (DefaultTableModel) table2.getModel();
        ArrayList<Isitabel> list = Isitabell();
        Object rowData[] = new Object[6];
        for(int i = 0; i < list.size(); i++)
        {
            rowData[0] = list.get(i).license;
            rowData[1] = list.get(i).brand;
            rowData[2] = list.get(i).production;
            rowData[3] = list.get(i).type;
            rowData[4] = list.get(i).color;
            rowData[5] = list.get(i).price;
            tblModel.addRow(rowData);
        }
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtLicense = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        production = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        txtOrderBY1 = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtProduction = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        price1 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtImage = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        txtLicense.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("ORDER BY");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Car Selection");

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LICENSE PLATE", "BRAND", "PRODUCTION YEAR", "TYPE", "COLOR", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table2);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4213475_arrow_back_left_return_icon.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("Car List");

        brand.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        brand.setText("LICENSE PLATE");

        production.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        production.setText("BRAND");

        type.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        type.setText("PRODUCTION");

        color.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        color.setText("TYPE");

        price.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        price.setText("COLOR");

        txtOrderBY1.setEditable(false);
        txtOrderBY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderBY1ActionPerformed(evt);
            }
        });

        txtBrand.setEditable(false);

        txtProduction.setEditable(false);

        txtType.setEditable(false);

        txtColor.setEditable(false);

        price1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        price1.setText("PRICE / DAY");

        txtPrice.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setText("Image");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/6934310_delivery_send_share_icon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/car2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtProduction, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(production, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(brand)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOrderBY1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(136, 136, 136)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(color)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(238, 238, 238)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5)))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(color)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrderBY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brand)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(production, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtImage, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        DefaultTableModel tblModel = (DefaultTableModel)table2.getModel();
        
        String data1 = tblModel.getValueAt(table2.getSelectedRow(),0).toString();
        String data2 = tblModel.getValueAt(table2.getSelectedRow(),1).toString();
        String data3 = tblModel.getValueAt(table2.getSelectedRow(),2).toString();
        String data4 = tblModel.getValueAt(table2.getSelectedRow(),3).toString();
        String data5 = tblModel.getValueAt(table2.getSelectedRow(),4).toString();
        String data6 = tblModel.getValueAt(table2.getSelectedRow(),5).toString();
        
        txtLicense.setText(data1);
        txtBrand.setText(data2);
        txtProduction.setText(data3);
        txtType.setText(data4);
        txtColor.setText(data5);
        txtPrice.setText(data6);
        
        {
            
            if (txtType.getText().equals("Avanza")&&(txtProduction.getText().equals("2012"))){
       
      
        ImageIcon myImage=new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/caravanza.jpeg")));
        Image img1=myImage.getImage();
        Image img2=img1.getScaledInstance(txtImage.getWidth(), txtImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        txtImage.setIcon(i);
                
            }
        
            
            if (txtType.getText().equals("Avanza")&&(txtProduction.getText().equals("2013"))){
       
      
        ImageIcon myImage=new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/toyota_avanza_2013_black.jpg")));
        Image img1=myImage.getImage();
        Image img2=img1.getScaledInstance(txtImage.getWidth(), txtImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        txtImage.setIcon(i);
                
            }
            
            if (txtType.getText().equals("Xenia")&&(txtProduction.getText().equals("2008"))){
       
      
        ImageIcon myImage=new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/daihatsu_xenia_2008_silver.jpg")));
        Image img1=myImage.getImage();
        Image img2=img1.getScaledInstance(txtImage.getWidth(), txtImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        txtImage.setIcon(i);
                
            }
            if (txtType.getText().equals("Jazz")&&(txtProduction.getText().equals("2011"))){
       
      
        ImageIcon myImage=new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/honda_jazz_2011_red.jpg")));
        Image img1=myImage.getImage();
        Image img2=img1.getScaledInstance(txtImage.getWidth(), txtImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        txtImage.setIcon(i);
                
            }
            if (txtType.getText().equals("Freed")&&(txtProduction.getText().equals("2010"))){
       
      
        ImageIcon myImage=new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/honda_freed_2010_white.jpg")));
        Image img1=myImage.getImage();
        Image img2=img1.getScaledInstance(txtImage.getWidth(), txtImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        txtImage.setIcon(i);
                
            }
                if (txtType.getText().equals("Luxio")&&(txtProduction.getText().equals("2010"))){
       
      
        ImageIcon myImage=new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/daihatsu_luxio_2010_black.png")));
        Image img1=myImage.getImage();
        Image img2=img1.getScaledInstance(txtImage.getWidth(), txtImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        txtImage.setIcon(i);
                
            }
                if (txtType.getText().equals("Yaris")&&(txtProduction.getText().equals("2009"))){
       
      
        ImageIcon myImage=new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/toyota_yaris_2008_white.jpg")));
        Image img1=myImage.getImage();
        Image img2=img1.getScaledInstance(txtImage.getWidth(), txtImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        txtImage.setIcon(i);
                
            }
                if (txtType.getText().equals("Mobilio")&&(txtProduction.getText().equals("2015"))){
       
      
        ImageIcon myImage=new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/honda_mobilio_2015_silver.jpg")));
        Image img1=myImage.getImage();
        Image img2=img1.getScaledInstance(txtImage.getWidth(), txtImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        txtImage.setIcon(i);
                
            }
                if (txtType.getText().equals("Xenia")&&(txtProduction.getText().equals("2009"))){
       
      
        ImageIcon myImage=new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/daihatsu_xenia_2009_red.jpg")));
        Image img1=myImage.getImage();
        Image img2=img1.getScaledInstance(txtImage.getWidth(), txtImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        txtImage.setIcon(i);
                
            }
                
                 if (txtType.getText().equals("Yaris")&&(txtProduction.getText().equals("2011"))){
       
      
        ImageIcon myImage=new ImageIcon (Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/toyota_yaris_2011_white.jpg")));
        Image img1=myImage.getImage();
        Image img2=img1.getScaledInstance(txtImage.getWidth(), txtImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        txtImage.setIcon(i);
                
            }
                
        
        
        
            
        }
    }//GEN-LAST:event_table2MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int dialogreturn = JOptionPane.showOptionDialog(this, "Are You Sure?", "Return",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);{

            if(dialogreturn == JOptionPane.YES_OPTION){
                CustomerInput jf1 = new CustomerInput();
                jf1.show();
                dispose();

                if (dialogreturn == JOptionPane.NO_OPTION){
                    remove(dialogreturn);
                }
            }
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txtOrderBY1.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Please Fill The Required Info !!");
        }else{
            
            int dialog = JOptionPane.showOptionDialog(this, "Are you Sure?", "Check",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);{
                    
            if(dialog == JOptionPane.YES_OPTION){
            
            RentalTransaction a =new RentalTransaction();
            RentalTransaction.txtOrderby2.setText(txtOrderBY1.getText());
            RentalTransaction.txtLisense1.setText(txtLicense.getText());
            RentalTransaction.txtBrand1.setText(txtBrand.getText());
            RentalTransaction.txtType1.setText(txtType.getText());
            RentalTransaction.txtColor1.setText(txtColor.getText());
            RentalTransaction.txtYear1.setText(txtProduction.getText());
            RentalTransaction.txtPrice1.setText(txtPrice.getText());
            a.setVisible(true);
            dispose();
            
            if (dialog == JOptionPane.NO_OPTION){
            
             remove(dialog); } 
            }
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtOrderBY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderBY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderBY1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brand;
    private javax.swing.JLabel color;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel price1;
    private javax.swing.JLabel production;
    private javax.swing.JTable table2;
    public static javax.swing.JTextField txtBrand;
    public static javax.swing.JTextField txtColor;
    private javax.swing.JLabel txtImage;
    public static javax.swing.JTextField txtLicense;
    public static javax.swing.JTextField txtOrderBY1;
    public static javax.swing.JTextField txtPrice;
    public static javax.swing.JTextField txtProduction;
    public static javax.swing.JTextField txtType;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
