/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Process;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yuman
 */
public class CustomerInput extends javax.swing.JFrame {

    /**
     * Creates new form CustomerInput
     */
    public CustomerInput() {
        initComponents();
        setLocationRelativeTo(null);
    }
   
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKtp = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPhonenumber = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        txtorder = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 186, 231));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Customer Data");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 286, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("KTP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 160, 89, 27));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 205, 104, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("ORDER BY");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 130, 27));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("PHONE NUMBER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 165, -1, -1));

        txtKtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKtpActionPerformed(evt);
            }
        });
        txtKtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKtpKeyPressed(evt);
            }
        });
        jPanel1.add(txtKtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 161, 194, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 208, 192, -1));

        txtPhonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhonenumberActionPerformed(evt);
            }
        });
        txtPhonenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhonenumberKeyPressed(evt);
            }
        });
        jPanel1.add(txtPhonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 161, 181, -1));

        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddressKeyPressed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 181, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KTP", "NAME", "PHONE NUMBER", "ADDRESS"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 378, 860, 180));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 128, -1));

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 128, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/6934310_delivery_send_share_icon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 120, 50));

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 128, -1));

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 128, -1));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4213475_arrow_back_left_return_icon.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 34, 58, 48));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1564534_customer_man_user_account_profile_icon.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));

        txtorder.setEditable(false);
        txtorder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtorderKeyPressed(evt);
            }
        });
        jPanel1.add(txtorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 181, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel7.setText("ADDRESS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 207, 83, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if ((((txtKtp.getText().equals(""))&&(txtName.getText().equals("")&&(txtAddress.getText().equals("")&&(txtPhonenumber.getText().equals(""))))))){
         JOptionPane.showMessageDialog(null,"Please Fill The Required Info !!");
       txtKtp.requestFocus();
      }
        txtKtp.setText("");
        txtName.setText("");
        txtAddress.setText("");
        txtPhonenumber.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtKtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKtpActionPerformed
    
        
    }//GEN-LAST:event_txtKtpActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String data1,data2,data3,data4;
        data1=txtKtp.getText();
        data2=txtName.getText();
        data3=txtPhonenumber.getText();
        data4=txtAddress.getText();
        
         if ((((txtKtp.getText().equals(""))&&(txtName.getText().equals("")&&(txtAddress.getText().equals("")&&(txtPhonenumber.getText().equals("")))))))
         {
             JOptionPane.showMessageDialog(null,"Please Fill The Required Info !!");}
             
              else if (txtKtp.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Please Fill Ktp !!");
         txtKtp.requestFocus();
            
         }
               else if (txtName.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Please Fill Name !!");
         txtName.requestFocus();
            
         }
           
                else if (txtPhonenumber.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Please Fill Phonenumber !!");
         txtPhonenumber.requestFocus();
         }
                
                else if (txtAddress.getText().equals("")){
         JOptionPane.showMessageDialog(null,"Please Fill Address !!");
         txtAddress.requestFocus();
         }
               
         else{
         JOptionPane.showMessageDialog(this,"Input Successfully..");
         Object[] row  = {data1,data2,data3,data4};
       DefaultTableModel model=(DefaultTableModel) table1.getModel();
       model.addRow(row);
       {
           
       txtorder.setText(txtName.getText());
    }
      txtKtp.setText("");
    txtName.setText("");
    txtAddress.setText("");
    txtPhonenumber.setText("");
    txtKtp.requestFocus();
    
         }
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String data1,data2,data3,data4;
    DefaultTableModel model = (DefaultTableModel) table1.getModel();
    if(table1.getSelectedRowCount()==1){
        data1=txtKtp.getText();
        data2=txtName.getText();
        data3=txtPhonenumber.getText();
        data4=txtAddress.getText();

    table1.setValueAt(data1,table1.getSelectedRow(),0);
     table1.setValueAt(data2,table1.getSelectedRow(),1);
     table1.setValueAt(data3,table1.getSelectedRow(),2);
     table1.setValueAt(data4,table1.getSelectedRow(),3);
     
    JOptionPane.showMessageDialog(this,"Update Successfully..");
       txtKtp.getText();
       txtName.getText();
       txtPhonenumber.getText();
       txtAddress.getText();
      
    }                                        
    else {
    if(table1.getRowCount()==0){
        
    JOptionPane.showMessageDialog(this,"Table Is Empty..");
    }
    else {
            JOptionPane.showMessageDialog(this,"Please Select Single Row For Update");
            }  
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        DefaultTableModel tblModel = (DefaultTableModel) table1.getModel();
        
        if(table1.getSelectedRowCount()==1){
                         int dialog = JOptionPane.showOptionDialog(this, "Delete This Data?", "Delete",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);{
            
        
             if(dialog == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Delete Successfully");
            
            tblModel.removeRow(table1.getSelectedRow());
             
            txtKtp.setText("");
             txtName.setText("");
             txtAddress.setText("");
             txtPhonenumber.setText("");
             txtAddress.setText("");
             txtorder.setText("");
            
             
        if (dialog == JOptionPane.NO_OPTION){
            
             remove(dialog); } 
             }
        }
            
    }

            
            
        else{
            if(table1.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Table Is Empty..");
            }else{
             JOptionPane.showMessageDialog(this, "Please Select Single Row For Delete");
            }
                      
                }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtKtpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKtpKeyPressed
        String Ktp = txtKtp.getText();
        int length = Ktp.length();
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            
            
            if (length<16){
                txtKtp.setEditable(true);
            }else{
              txtKtp.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE  ) {
             txtKtp.setEditable(true);
             
            }else{
                txtKtp.setEditable(false);
            }
            
        }
            
        
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            txtName.requestFocus();
    }//GEN-LAST:event_txtKtpKeyPressed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            txtPhonenumber.requestFocus();
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtPhonenumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhonenumberKeyPressed
        String phonenumber = txtPhonenumber.getText();
        int length = phonenumber.length();
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<12){
                txtPhonenumber.setEditable(true);
            }else{
              txtPhonenumber.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE  ) {
             txtPhonenumber.setEditable(true);
             
            }else{
                txtPhonenumber.setEditable(false);
            }
            
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            txtAddress.requestFocus();
    }//GEN-LAST:event_txtPhonenumberKeyPressed

    private void txtAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyPressed
         if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            jButton4.doClick();
    }//GEN-LAST:event_txtAddressKeyPressed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int dialogreturn = JOptionPane.showOptionDialog(this, "Are You Sure?", "Return",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);{
        
        if(dialogreturn == JOptionPane.YES_OPTION){
         Dashbord jf1 = new Dashbord();
        jf1.show();
        dispose();
        
          if (dialogreturn == JOptionPane.NO_OPTION){
             remove(dialogreturn); 
          }
        }
    }
                                  

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPhonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhonenumberActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        DefaultTableModel tblModel = (DefaultTableModel)table1.getModel();

        String data1 = tblModel.getValueAt(table1.getSelectedRow(),0).toString();
        String data2 = tblModel.getValueAt(table1.getSelectedRow(),1).toString();
        String data3 = tblModel.getValueAt(table1.getSelectedRow(),2).toString();
        String data4 = tblModel.getValueAt(table1.getSelectedRow(),3).toString();


        txtKtp.setText(data1);
        txtName.setText(data2);
        txtorder.setText(data2);
        txtPhonenumber.setText(data3);
        txtAddress.setText(data4);
        
    }//GEN-LAST:event_table1MouseClicked

    private void txtorderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtorderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtorderKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (txtorder.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Please Fill The Required Info !!");
        }else{
        CarSelection page2 =new CarSelection();
       CarSelection.txtOrderBY1.setText(txtorder.getText());
        page2.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable table1;
    public static javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtKtp;
    public static javax.swing.JTextField txtName;
    public static javax.swing.JTextField txtPhonenumber;
    public static javax.swing.JTextField txtorder;
    // End of variables declaration//GEN-END:variables
}
