/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Process;

import static Process.CustomerInput.txtorder;
import java.awt.event.KeyEvent;
import javax.lang.model.element.NestingKind;
import javax.swing.JOptionPane;

/**
 *
 * @author yuman
 */
public class RentalTransaction extends javax.swing.JFrame{

    /**
     * Creates new form CarSelection
     */
    public RentalTransaction() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOrderby2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPay = new javax.swing.JTextField();
        cb_1 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtYear1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtChange = new javax.swing.JTextField();
        txtLisense1 = new javax.swing.JTextField();
        txtType1 = new javax.swing.JTextField();
        txtColor1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtBrand1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 178, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Transaction");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(390, 0, 210, 144);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setText("ORDER DATA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 190, 140, 16);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setText("CAR DATA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 260, 100, 16);

        txtOrderby2.setEditable(false);
        txtOrderby2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtOrderby2);
        txtOrderby2.setBounds(230, 180, 190, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setText("TOTAL");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 460, 120, 16);

        txtPrice1.setEditable(false);
        txtPrice1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtPrice1);
        txtPrice1.setBounds(230, 320, 190, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setText("PRICE");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 330, 120, 16);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel6.setText("LOAN DURATION");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 400, 120, 16);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel7.setText("MONEY CHANGE");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 600, 110, 16);

        txtPay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPayKeyPressed(evt);
            }
        });
        jPanel1.add(txtPay);
        txtPay.setBounds(230, 520, 290, 40);

        cb_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select Duration..", "1 Day", "2 Days", "3 Days" }));
        cb_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_1ActionPerformed(evt);
            }
        });
        jPanel1.add(cb_1);
        cb_1.setBounds(230, 392, 210, 30);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/4213475_arrow_back_left_return_icon.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(40, 30, 80, 60);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(460, 210, 41, 30);

        txtTotal.setEditable(false);
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTotalKeyPressed(evt);
            }
        });
        jPanel1.add(txtTotal);
        txtTotal.setBounds(230, 450, 290, 40);

        txtYear1.setEditable(false);
        txtYear1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtYear1);
        txtYear1.setBounds(920, 250, 80, 30);

        jButton1.setText("=");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(550, 530, 41, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel9.setText("PAY");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 540, 50, 16);

        txtChange.setEditable(false);
        txtChange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChangeKeyPressed(evt);
            }
        });
        jPanel1.add(txtChange);
        txtChange.setBounds(230, 590, 290, 40);

        txtLisense1.setEditable(false);
        txtLisense1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtLisense1);
        txtLisense1.setBounds(230, 250, 190, 30);

        txtType1.setEditable(false);
        txtType1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtType1);
        txtType1.setBounds(620, 250, 140, 30);

        txtColor1.setEditable(false);
        txtColor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtColor1);
        txtColor1.setBounds(770, 250, 140, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/7340559_e-commerce_online_shopping_ui_receipt_icon.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(610, 40, 80, 60);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/6934310_delivery_send_share_icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(840, 600, 120, 50);

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 3, 24)); // NOI18N
        jLabel11.setText("Next Page");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(840, 560, 130, 32);

        txtBrand1.setEditable(false);
        txtBrand1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBrand1);
        txtBrand1.setBounds(440, 250, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int dialogreturn = JOptionPane.showOptionDialog(this, "Are You Sure?", "Return",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);{

            if(dialogreturn == JOptionPane.YES_OPTION){
                CarSelection jf1 = new CarSelection();
                jf1.show();
                dispose();

                if (dialogreturn == JOptionPane.NO_OPTION){
                    remove(dialogreturn);
                }
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
      
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyPressed
     
                                             
    }//GEN-LAST:event_txtTotalKeyPressed

    private void cb_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_1ActionPerformed
       
      int a=0;
      int c=0;
      a = Integer.parseInt(txtPrice1.getText());
      
      String pilih = (String) cb_1.getSelectedItem();
      
       if (pilih=="1 Day") {
            c = a*1;
            
     
        }else if (pilih=="2 Days") {
            c= a*2;
   
        }else if (pilih=="3 Days") {
            c= a*3; 
          
        }
      txtTotal.setText(Integer.toString(c));
        
    }//GEN-LAST:event_cb_1ActionPerformed

    private void txtPayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPayKeyPressed
       String pay = txtPay.getText();
        int length = pay.length();
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<12){
                txtPay.setEditable(true);
            }else{
              txtPay.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE  ) {
             txtPay.setEditable(true);
             
            }else{
                txtPay.setEditable(false);
            }
            
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            txtPay.requestFocus();
    }//GEN-LAST:event_txtPayKeyPressed

    private void txtChangeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChangeKeyPressed
          String change = txtChange.getText();
        int length = change.length();
        char c = evt.getKeyChar();
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<12){
                txtChange.setEditable(true);
            }else{
              txtChange.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE  ) {
            txtChange.setEditable(true);
             
            }else{
                txtChange.setEditable(false);
            }
            
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            txtChange.requestFocus();
    }//GEN-LAST:event_txtChangeKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int a,b,c;
        a = Integer.parseInt(txtTotal.getText());
        b = Integer.parseInt(txtPay.getText());
        
        if (b<=a) {
            JOptionPane.showMessageDialog(null, "Please Pay With The Right Amount!!");
        }else{
        c=b-a;
         this.txtChange.setText(Integer.toString(c));
        }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if (txtPay.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Please Fill The Required Info !!");
        }else{
        Transcript page2 =new Transcript();
        page2.setVisible(true);
        dispose();
        
       
        Transcript.jTextArea1.setText("Name  :"+" "+txtOrderby2.getText()+("\nCar Data  :")+("\nLicense Plate  :")+
                (" ")+txtLisense1.getText()+("\nBrand  :")+(" ")+txtBrand1.getText()+("\nType  :")+
                (" ")+txtType1.getText()+("\nColor  :")+(" ")+txtColor1.getText()+("\nProduction Year  :")+
                (" ")+(txtYear1.getText()+("\nLoan Time  :")+(" ")+cb_1.getSelectedItem()+("\nPrice  :")+
                (" ")+("Rp ")+txtPrice1.getText()+("\nTotal  :")+(" ")+("Rp ")+txtTotal.getText()+("\nPay  :")+(" ")+
                        ("Rp ")+txtPay.getText()+("\nMoney Change  :")+(" ")+("Rp ")+txtChange.getText()));                                                                              
        
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentalTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    public static javax.swing.JTextField txtBrand1;
    private javax.swing.JTextField txtChange;
    public static javax.swing.JTextField txtColor1;
    public static javax.swing.JTextField txtLisense1;
    public static javax.swing.JTextField txtOrderby2;
    private javax.swing.JTextField txtPay;
    public static javax.swing.JTextField txtPrice1;
    private javax.swing.JTextField txtTotal;
    public static javax.swing.JTextField txtType1;
    public static javax.swing.JTextField txtYear1;
    // End of variables declaration//GEN-END:variables
}

